// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

library World {
    enum TerrainType {
        SAND,
        OCEAN,
        LAND
    }

    string public constant terrain =
        "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSOOSSSSSSSSSSSSSSSSSSSSSSSSSSSSOOOOSSSSSSSSSSSSSSSSSSSSSSSSSSOOOOOOSSSSSSSSSSSSSSSSSSSSSSSSOOOOOOOOSSSSSSSSSSSSSSSSSSSSSSSOOOOOOOOOSSSSSSSSSSSSSSSSSSSSSOOOOOOOOOOLSSSSSSSSSSSSSSSSSSSOOOOOOOOOOLLLSSSSSSSSSSSSSSSSSSOOOOOOOOOOLLLLSSSSSSSSSSSSSSSSSOOOOOOOOOLLLLLLSSSSSSSSSSSSSSSSOOOOOOOOLLLLLLLLSSSSSSSSSSSSSSSOOOOOOOLLLLLLLLLLSSSSSSSSSSSSSOOOOOOOOLLLLLLLLLLLSSSSSSSSSSSSSOOOOOOOLLLLLLLLLLLLSSSSSSSSSSSOOOOOOOOLLLLLLLLLLLLLOSSSSSSSSSOOOOOOOOLLLLLLLLLLLLLLOOSSSSSSSOOOOOOOOLLLLLLLLLLLLLLLOOOSSSOOOOOOOOOOLLLLLLLLLLLLLLLLOOOOOOOOOOOOOOOLLLLLLLLLLLLLLLLLOOOOOOOOOOOOOOOLLLLLLLLLLLLLLLLLOOOOOOOOOOOOOOLLLLLLLLLLLLLLLLLLOOOOOOOOOOOOOOLLLLLLLLLLLLLLLLLLOOOOOOOOOOOOOOLLLLLLLLLLLLLLLLLLOOOOOOOOOOOOOOLLLLLLLLLLLLLLLLLLOOOOOOOOOOOOOLLLLLLLLLLLLLLLLLLLOOOOOOOOOOOOOLLLLLLLLLLLLLLLLLLLOOOOOOOOOOOOOLLLLLLLLLLLLLLLLLLLOOOOOOOOOOOOOLLLLLLLLLLLLLLLLLLLOOOOOOOOOOOOLLLLLLLLLLLLLLLLLLLLOOOOOOOOOOOOLLLLLLLLLLLLLLLLLLLLOOOOOOOOOOOLLLLLLLLLLLLLLLLLLLLLOOOOOOOOOOLLLLLLLLLLLLLLLLLLLLLLOOOOOOOOOLLLLLLLLLLLLLLLLLLLLLLL";

    function getWorld() public pure returns (TerrainType[32][32] memory) {
        TerrainType[32][32] memory world;

        // total length of terrain string is 1024. if character is S then SAND, if O then OCEAN, if L then LAND.

        uint256 index = 0;
        for (uint256 i = 0; i < 32; i++) {
            for (uint256 j = 0; j < 32; j++) {
                if (bytes(terrain)[index] == "S") {
                    world[i][j] = TerrainType.SAND;
                } else if (bytes(terrain)[index] == "O") {
                    world[i][j] = TerrainType.OCEAN;
                } else if (bytes(terrain)[index] == "L") {
                    world[i][j] = TerrainType.LAND;
                }
                index++;
            }
        }

        return world;
    }
}
